version: '3.3'

services:

  apache_next_proc:
    hostname: apache_next_proc
    container_name: apache_next_proc
    build: ./apache_next_proc
    environment:
      PLATFORM_IP: 'virtuoso'
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    ports:
      - "8080:80"
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
          labels: "apacheweb-log"
    networks:
      - virtuoso
    #restart: always

  virtuoso:
    #image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    image: openlink/virtuoso-opensource-7:latest
    hostname: virtuoso
    container_name: virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      DBA_PASSWORD: "dba"
      VIRT_Parameters_NumberOfBuffers: 680000
      VIRT_Parameters_MaxDirtyBuffers: 500000
      VIRT_Parameters_ThreadCleanupInterval: 0
      VIRT_Parameters_ThreadThreshold: 0
      VIRT_Database_MaxCheckpointRemap: 150000
      VIRT_Parameters_CheckpointInterval: 60
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    ports:
      - "8890:8890"
      - "1111:1111"
    volumes:
      - ./data/virtuoso:/data
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
          labels: "virtuoso-log"
    networks:
      - virtuoso
    #restart: always

  pipeline:
      hostname: pipeline
      container_name: pipeline
      build: ./pipeline
      ports:
        - '5000:5000'
      environment:
        API_PORT: 5000
        PLATFORM_IP: 'virtuoso'
        LOG_DIR: "/mnt/log"
        LOG_LEVEL: "info"
        LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
      volumes: 
        - pipeline_input_data:/pipeline/data/
        - log:/mnt/log
      networks: 
       - virtuoso
      restart: always
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
          labels: "pipeline-log"

#  yasgui:
#    image: erikap/yasgui
#    container_name: yasgui
#    ports:
#      - "3040:80"
#    environment:
#      #DEFAULT_SPARQL_ENDPOINT: "https://nextprocurement.linkeddata.es/sparql"
#      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"
#        labels: "yasgui-log"

networks:
  virtuoso:
    #name: virtuoso_platform

volumes: 
  pipeline_input_data:
    driver: local
  log:
    driver: local
  db-data:
